---
title: "Assignment 1: Introduction"
author: "Ben Culberson"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Lima_A01_Introduction.Rmd") prior to submission.

The completed exercise is due on <>.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have had several classes and projects that deal with both statistical analysis and R, including Time Series Analysis last year. In that class, I used Git as a means of interfacing with the lessons and assignments.

2. Are there any components of the course about which you feel confident?

> Answer: I feel reasonably competent at github and R studio, but not enough for me to brag about it. I think I'll need a refresher for both in this course. Some of the basic R functions come back to me quickly, but a further dive into data analytics is why I'm here.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I'm a little nervous about keeping this class balanced with everything else, but other than that I'm happy.


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/benculberson/Environmental_Data_Analytics_2022.git


